### ISSUE TITLE
Recipe improvements: with_unit_tests

### ISSUE THREAD

**Issue by lasote** [bincrafters/conan-icu#2]
https://github.com/bincrafters/conan-icu/blob/a21d12ba91f1b2ae1493f962a85cb13688440710/conanfile.py#L200

Running the tests are not really generating a different package, right? or are you packaging the tests intentionally? If the package is not changing maybe you could write a `package_id()` method and ensure that that option do not affect the package identifier:

```
def package_id(self):
    self.info.options.with_unit_tests = "any" # or any other value
```

**Comment by solvingj** [comment]
Done
