### ISSUE TITLE
Recipe improvements: msys as a build_require?

### ISSUE THREAD

**Issue by lasote** [bincrafters/conan-icu#3]
https://github.com/bincrafters/conan-icu/blob/a21d12ba91f1b2ae1493f962a85cb13688440710/conanfile.py#L73

Is the msys package only needed to build a package? or it's needed for runtime too? If it's only for building you can use a `build_require`, that guarantee that won't be downloaded unless you need to build a binary package.

**Comment by solvingj** [comment]
done.  interesting to note that `requires` has an addmethod (`self.requires.add()`) while for `build_requires` is just the name of the method (`self.build_requires()`) .
