### ISSUE TITLE
Recipe improvements: Extract detections to different function 

### ISSUE THREAD

**Issue by lasote** [bincrafters/conan-icu#4]
https://github.com/bincrafters/conan-icu/blob/a21d12ba91f1b2ae1493f962a85cb13688440710/conanfile.py#L152-L178

The build method is really hard to read. Maybe splitting it into some methods, for example, the detection of the msys, etc. I don't know if it could be interesting for general purpose in the conan code base, we could think about it.

**Comment by solvingj** [comment]
I agree in general, will improve this when we get another round of time to refactor.
