### ISSUE TITLE
Recipe improvements: package in local cache will be deprecated

### ISSUE THREAD

**Issue by lasote** [bincrafters/conan-icu#5]
https://github.com/bincrafters/conan-icu/blob/a21d12ba91f1b2ae1493f962a85cb13688440710/conanfile.py#L24

From 0.27, In favor of the use of local commands, conan build + conan package

**Comment by solvingj** [comment]
Isn't conan export fundamentally different than conan build?  Export just updates the recipe in cache, quick and easy and includes any "packaging" changes.  conan build is a full re-run of the build (right?)

**Comment by solvingj** [comment]
removed reference to this from comments
